os: osx
rvm: system

language: ruby
matrix:
  include:
    - env: OSX=10.13
      osx_image: xcode10.1

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  - export TRAVIS_COMMIT="$(git rev-parse --verify -q HEAD)"
  - if [ -f ".git/shallow" ]; then
    travis_retry git fetch --unshallow;
    fi
  - sudo chown -R $USER "$(brew --repo)"
  - git -C "$(brew --repo)" reset --hard origin/master
  - git -C "$(brew --repo)" clean -qxdff
  - export HOMEBREW_DEVELOPER="1"
  - brew update || brew update
  - rm -rf "$(brew --repo $TRAVIS_REPO_SLUG)"
  - mkdir -p "$(brew --repo $TRAVIS_REPO_SLUG)"
  - rsync -az "$TRAVIS_BUILD_DIR/" "$(brew --repo $TRAVIS_REPO_SLUG)"
  - export TRAVIS_BUILD_DIR="$(brew --repo $TRAVIS_REPO_SLUG)"
  - cd "$(brew --repo)"
  - ulimit -n 1024

script:
  # Homebrew style checks
  - brew audit $(brew --repo $TRAVIS_REPO_SLUG)/Formula/*.rb
  - brew style $(brew --repo $TRAVIS_REPO_SLUG)/Formula/*.rb
  # Install supported packages
  # ---- gcc-arm-none-eabi
  - brew install gcc-arm-none-eabi-53
  - brew unlink gcc-arm-none-eabi-53
  - brew install gcc-arm-none-eabi-63
  - brew unlink gcc-arm-none-eabi-63
  # ---- clang-llvm
  - brew install clang-llvm-400
  - brew unlink clang-llvm-400
  # ---- skycoin-cx
  - brew install skycoin-cx
  - brew unlink skycoin-cx
   # ---- skycoin-cli
  - brew install skycoin-cli
  - brew unlink skycoin-cli
  # ---- objconv
  - brew install objconv
  - brew unlink objconv
  # Install extra packages
  # ---- gcc-arm-none-eabi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    brew install gcc-arm-none-eabi-47 ;
    brew unlink gcc-arm-none-eabi-47 ;
    fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    brew install gcc-arm-none-eabi-48 ;
    brew unlink gcc-arm-none-eabi-48 ;
    fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    brew install gcc-arm-none-eabi-49 ;
    brew unlink gcc-arm-none-eabi-49 ;
    fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    brew install gcc-arm-none-eabi-54 ;
    brew unlink gcc-arm-none-eabi-54 ;
    fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    brew install gcc-arm-none-eabi-62 ;
    brew unlink gcc-arm-none-eabi-62 ;
    fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    brew install gcc-arm-none-eabi-74 ;
    brew unlink gcc-arm-none-eabi-74 ;
    fi
  # ---- clang-llvm
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    brew install clang-llvm-401 ;
    brew unlink clang-llvm-401 ;
    fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    brew install clang-llvm-500 ;
    brew unlink clang-llvm-500 ;
    fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    brew install clang-llvm-501 ;
    brew unlink clang-llvm-501 ;
    fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    brew install clang-llvm-502 ;
    brew unlink clang-llvm-502 ;
    fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    brew install clang-llvm-600 ;
    brew unlink clang-llvm-600 ;
    fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    brew install clang-llvm-700 ;
    brew unlink clang-llvm-700 ;
    fi
